# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 14:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('point', django.contrib.gis.db.models.fields.PointField(help_text='Represented as (longitude, latitude)', srid=4326)),
                ('bearing', models.FloatField()),
                ('altitud', models.FloatField()),
                ('speed', models.FloatField()),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
