# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fecha',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='hora',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
