# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20170427_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
    ]
