# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_location_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fecha2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
