# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20170430_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Direccion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Nombre_Contacto',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Rubro',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Telefono',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Telefono_Contacto',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Empresa',
            field=models.CharField(blank=True, choices=[('AirForceOne', 'AirForceOne'), ('Pedorro', 'Pedorro'), ('Aero 1', 'Aero 1'), ('Pizza pepe', 'Pizza pepe')], max_length=30, null=True),
        ),
    ]
