# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20170502_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Tipo_Cuenta',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Cliente', 'Cliente'), ('Chequeo', 'Chequeo'), ('Individual', 'Individual')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Cuenta_Activa',
            field=models.BooleanField(default=False),
        ),
    ]
