# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20170607_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Empresa',
            field=models.ManyToManyField(blank=True, to='clientes._empresas'),
        ),
    ]
