# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20170607_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_empresas',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
