# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20170607_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Email',
            new_name='Email_Alternativo_de_Contacto',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Empresa',
            field=models.ManyToManyField(to='clientes._empresas'),
        ),
    ]
