# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20170607_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Cuentas_Asociadas',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Asociado_A_Cuenta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
