# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20170623_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
